## Numpy

In [2]:
# Numpy - Numerical python

# simplify arithmetic actions/ matrix

# https://numpy.org/ - documentation

import numpy as np


In [4]:
# int, list, dict, set
# array


ls = [1,2,3,4]
arr1 = np.array(ls)
print(ls)
print(arr1)

[1, 2, 3, 4]
[1 2 3 4]


In [6]:
# c#, c++ - low level lang meaning that hard to understand for humans but easier for machines
#  + faster than python


# dimensions

ls2 = [[1,2,3], [4,5,6]]
arr2 = np.array(ls2)
print(arr2)


[[1 2 3]
 [4 5 6]]


In [13]:
ls3 = [[[1,2],[3,4]], [[5,6],[7,8]]]
arr3 = np.array(ls3)
print(arr3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# array methods (min, max) and attributes (shape)


# size - number of elements
print(arr1.size)
print(arr2.size)
print(arr3.size)

4
6
8


In [19]:
# ndim - dimension

print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


In [22]:
# shape - shows as the table
# first num being row, last as column, middle - number of elements

print(arr1.shape) # first one row, second as column
print(arr2.shape)
print(arr3.shape)

(4,)
(2, 3)
(2, 2, 2)


In [ ]:
# type of the arr + how much memory it takes from system
# can be changed for smaller arrays

print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

int64
int64
int64


In [27]:
# how much memory full arr takes

print(arr1.nbytes)

32


In [ ]:
# arange - same as range but in numpy

r = range(1,50,2)
r

range(1, 50, 2)

In [39]:
arange = np.arange(1,49,1)
print(arange.reshape(4,12))
print(arange.reshape(8,6))

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32 33 34 35 36]
 [37 38 39 40 41 42 43 44 45 46 47 48]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]]


In [48]:
# linspace - takes range and how many numbers to print and prints them with the same length

print(np.linspace(0,100,5))
print(np.linspace(0,100,10))

[  0.  25.  50.  75. 100.]
[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [50]:
# ones - 1 matrix with column and rows

np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [52]:
# same as ones but fills with 0

np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [56]:
# makes matrix with col and row from tuple and fills with the num given


np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [58]:
# matrix diagonally

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [68]:
# random - takes numbers randomly from range
# randint - takes only integers - possible to give arr shape for several values

np.random.randint(10,50, (2,3))

array([[25, 20, 48],
       [47, 47, 38]], dtype=int32)

In [ ]:
# randomly from standard normal distribution (mean 0, standard deviation 1)

np.random.randn(4,3)

array([[ 0.05678099, -1.19208655, -1.40432158],
       [ 0.98438888,  0.14628195, -0.62659005],
       [-0.2173289 , -0.06062518,  1.19805723],
       [ 0.36166938,  0.49062395,  1.18196541]])

In [99]:
# randomly from 0 to 1 [0,1)

np.random.rand(3,3)

array([[0.94437261, 0.88764571, 0.7943436 ],
       [0.01792543, 0.92216979, 0.94116793],
       [0.35776448, 0.09477199, 0.89746683]])

In [103]:
arr1[1:3]

array([2, 3])

In [111]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [113]:
# first row, then column

print(arr2[1])
print(arr2[1,1])
print(arr2[0,:])
print(arr2[:,1])

[4 5 6]
5
[1 2 3]
[2 5]


In [115]:
type(arr2)

numpy.ndarray

In [119]:
arr = np.array([1,2,3,4,5,6,7,8,9])

print(arr**2)
print(arr - 8)
print(arr + 50)

[ 1  4  9 16 25 36 49 64 81]
[-7 -6 -5 -4 -3 -2 -1  0  1]
[51 52 53 54 55 56 57 58 59]


In [126]:
# arr2 = np.random.randint(0,101, (10,10))
arr2 = np.arange(0,101)

print(arr2[arr2 % 2 == 0])
print(arr2[arr2 > 35])

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
[ 36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]


In [128]:
print(arr2[(arr2 > 35) & (arr2 < 50)])

[36 37 38 39 40 41 42 43 44 45 46 47 48 49]
